import type { Metadata } from 'next'
import Script from 'next/script'

import './globals.css'



export const metadata: Metadata = {
  title: '25+5Clock',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      </head>
      <body >{children}
      <Script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js" async />


      </body>
     
    </html>
  )
}
